[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel"]

build-backend = 'setuptools.build_meta'

[project.optional-dependencies]
docs =
    sphinx
    sphinx-automodapi
    numpydoc
    sphinx_rtd_theme